---
title: "Ability estimation methods"
author: "Piotr Król"
date: "07 08 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

Content:

* 

```{r libraries, warning=FALSE, message=FALSE}
library(mirt)
library(ggpubr)
```

```{r data loading, message=FALSE}
# responses_demo <- read.csv("Data/responses_demo.csv", encoding = "UTF-8")
# responses <- as.matrix(responses_demo[,5:ncol(responses_demo)])
# cdi <- read.csv("Data/cdi.csv", encoding = "UTF-8")
# load("Data/mod")
load("Data/ability_estimation.RData")
```

```{r model}
mod
```
```{r}
#fscores_EAP <- as.data.frame(fscores(mod, method = "EAP", full.scores.SE = T))
ggscatter(fscores_EAP, y = "SE_F1", x = "F1",
          xlab = "Theta", ylab = "SE",
          title = paste0("Mean SE = ", round(mean(fscores_EAP$SE_F1), 3), " Median SE = ", round(median(fscores_EAP$SE_F1), 3)))
```
```{r}
#fscores_EAP_401q <- as.data.frame(fscores(mod, method = "EAP", full.scores.SE = T, quadpts = 401))
ggscatter(fscores_EAP_401q, y = "SE_F1", x = "F1",
          xlab = "Theta", ylab = "SE",
          title = paste0("Mean SE = ", round(mean(fscores_EAP_401q$SE_F1), 3), " Median SE = ", round(median(fscores_EAP_401q$SE_F1), 3)))
```

```{r}
#fscores_MAP <- as.data.frame(fscores(mod, method = "MAP", full.scores.SE = T))
ggscatter(fscores_MAP, y = "SE_F1", x = "F1",
          xlab = "Theta", ylab = "SE",
          title = paste0("Mean SE = ", round(mean(fscores_MAP$SE_F1), 3), " Median SE = ", round(median(fscores_MAP$SE_F1), 3)))
```
```{r}
fscores_MAP_401q <- as.data.frame(fscores(mod, method = "MAP", full.scores.SE = T, quadpts = 401))
ggscatter(fscores_MAP_401q, y = "SE_F1", x = "F1",
          xlab = "Theta", ylab = "SE",
          title = paste0("Mean SE = ", round(mean(fscores_MAP_401q$SE_F1), 3), " Median SE = ", round(median(fscores_MAP_401q$SE_F1), 3)))
```

```{r}
#fscores_ML <- fscores(mod, method = "ML", full.scores.SE = T)
ggscatter(fscores_ML, y = "SE_F1", x = "F1",
          xlab = "Theta", ylab = "SE",
          title = paste0("Mean SE = ", round(mean(fscores_ML$SE_F1), 3), " Median SE = ", round(median(fscores_ML$SE_F1), 3)))
```


