---
title: "Early-stopping CAT simulations"
author: "Piotr Król"
date: "23 08 2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

Content:

* Plot ability vs. SE whole pool
* Simulation with SE = 0.15 stop criterion
* Simulation with SE = 0.1 stop criterion

```{r libraries, warning=F, message=F}
library(mirt)
library(mirtCAT)
library(parallel)
library(plyr)
library(ggpubr)
```

```{r data loading, eval=F}
responses_demo <- read.csv("Data/responses_demo.csv", encoding = "UTF-8")
responses <- as.matrix(responses_demo[,5:ncol(responses_demo)])
load("Data/items_to_remove")
load("Data/params")
load("Data/fscores")
responses <- responses[, -items_to_remove]
source(paste0(getwd(),"/get_sim_results.R"))
```

```{r data loading 2, include=F}
load("Data/early_stop_CAT.RData")
```

# Ability vs. SE whole pool

```{r fig.width = 12, fig.height = 8}
ggplot(fscores, aes(F1, SE_F1)) +
  geom_point(alpha = 0.3) +
  xlab("Ability level (Θ)") +
  ylab("Standard error (SE)") +
  labs(title = "CDI: WS production") +
  theme(
  panel.background = element_rect(fill = NA),
  panel.grid.major = element_line(colour = "lightgrey"),
  text = element_text(size=16)
)
```

```{r}
summary(fscores$SE_F1)
```
# Simulation with SE = 0.1 stop criterion

```{r eval=F}
mo <- generate.mirt_object(params, '2PL')
cl <- makeCluster(detectCores())
results_SE1 <- mirtCAT(mo = mo, method = "MAP", criteria = "MI", start_item = "MI", local_pattern = responses, cl = cl, design = list(min_SEM = 0.1))
```
```{r}
get_sim_results(results_SE1, fscores, params)
```

Plot distribution of tests lengths:

```{r fig.width=12, fig.height=8}
#Prepare cuts
tests_lengths <- laply(results_SE1, function(x) length(x$items_answered))
cuts <- cut(tests_lengths, breaks = c(0, 5, 10, 15, 25, 35, 50, 75, 100, 666, 667), labels = c("1 - 5", "6 - 10", "11 - 15", "16 - 25", "26 - 35", "36 - 50", "51 - 75", "76 - 100", "101 - 666", "667"))

#Plot
ggplot(data.frame(round(table(cuts) / nrow(responses) * 100, 1)), aes(x = cuts, y = Freq)) +
  xlab("Number of items administered") +
  ylab("Percent of respondents (%)") +
  geom_bar(stat = "identity") +
  labs(title = "CDI: WS production. SE = 0.1 stop criterion") +
  geom_text(aes(label = Freq), vjust = -0.3, size=6) + 
  theme_pubclean() +
  theme(text = element_text(size=16))
```

# Simulation with SE = 0.15 stop criterion

```{r eval=F}
results_SE15 <- mirtCAT(mo = mo, method = "MAP", criteria = "MI", start_item = "MI", local_pattern = responses, cl = cl, design = list(min_SEM = 0.15))
```
```{r}
get_sim_results(results_SE15, fscores, params)
```

Plot distribution of tests lengths:

```{r fig.width=12, fig.height=8}
#Prepare cuts
tests_lengths <- laply(results_SE15, function(x) length(x$items_answered))
cuts <- cut(tests_lengths, breaks = c(0, 5, 10, 15, 25, 35, 50, 75, 100, 666, 667), labels = c("1 - 5", "6 - 10", "11 - 15", "16 - 25", "26 - 35", "36 - 50", "51 - 75", "76 - 100", "101 - 666", "667"))

#Plot
ggplot(data.frame(round(table(cuts) / nrow(responses) * 100, 1)), aes(x = cuts, y = Freq)) +
  xlab("Number of items administered") +
  ylab("Percent of respondents (%)") +
  labs(title = "CDI: WS production. SE = 0.15 stop criterion") +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Freq), vjust = -0.3, size=6) + 
  theme_pubclean() +
  theme(text = element_text(size=16))
```

```{r fig.width=12, fig.height=8}
#Prepare cuts
cuts <- cut(tests_lengths, breaks = c(0, 50,  667), labels = c("1 - 50", "51 - 667"))

#Plot
ggplot(data.frame(round(table(cuts) / nrow(responses) * 100, 1)), aes(x = cuts, y = Freq)) +
  xlab("Number of items administered") +
  ylab("Percent of tests (%)") +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Freq), vjust = -0.3, size=6) + 
  theme_pubclean() +
  theme(text = element_text(size=16))
```

# SE vs. age

```{r fig.width=12, fig.height=8}
ggplot(data.frame(age = as.factor(responses_demo$months), SE = fscores$SE_F1), aes(age, SE)) +
  geom_boxplot() +
  xlab("Age (months)") +
  ylab("Standard error of ability estimations") +
  labs(title = "CDI: WS production") +
  theme(
  panel.background = element_rect(fill = NA),
  panel.grid.major = element_line(colour = "lightgrey"),
  text = element_text(size=16)
  )
```