---
title: "Items usage in CAT"
author: "Piotr Król"
date: "12 08 2021"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

```{r libraries, warning=F, message=F}
library(mirtCAT)
library(parallel)
library(ggpubr)
library(plyr)
```

```{r data loading, eval=T}
responses_demo <- read.csv("Data/responses_demo.csv", encoding = "UTF-8")
responses <- as.matrix(responses_demo[,5:ncol(responses_demo)])
cdi <- read.csv("Data/cdi.csv", encoding = "UTF-8")
load("Data/mod_r")
load("Data/items_to_remove")
load("Data/start_thetas")
responses <- responses[, -items_to_remove]
cdi <- cdi[!cdi$number.ws %in% items_to_remove, ]
```

```{r data loading 2, include=F}
load("Data/items_usage.RData")
```

```{r model}
mod <- mod_r
rm(mod_r)
mod
```
Investigate items parameters:

```{r}
params <- as.data.frame(coef(mod, simplify = T, IRTpars = T)$items)[1:2]
params <- cbind(params, cdi)
```

```{r}
ggplot(params, aes(b, a, colour=category, label=position)) +
  geom_text(check_overlap = T) +
  geom_point(alpha = 0.3) +
  xlab("Difficulty") +
  ylab("Discrimination") +
  labs(colour = "Category") +
  theme(
  panel.background = element_rect(fill = NA),
  panel.grid.major = element_line(colour = "grey"),
)
```
Make simulation with recommended settings:

```{r eval=F}
params <- as.data.frame(coef(mod, simplify = T)$items)[1:2]
mo <- generate.mirt_object(params, '2PL')
cl <- makeCluster(detectCores())
sim_results <- mirtCAT(mo = mo, method = "MAP", criteria = "MI", start_item = "MI", local_pattern = responses, cl = cl, design = list(min_items = 10, min_SEM = 0.1, max_items = 50))
save.image("Data/items_usage.RData")
```

Most popular items:

```{r}
raw_responses <- laply(sim_results, function(x) x$raw_responses)
item_usage <- round(apply(raw_responses, 2, function(x) length(which(!is.na(x))))/nrow(responses), 3)
most_popular <- cbind(cdi, item_usage)
most_popular <- most_popular[order(most_popular$item_usage, decreasing=T), ]
most_popular
```

Most popular categories:

```{r}
items_used <- apply(raw_responses, 1, function(x) which(!is.na(x)))
categories_used <- cdi[unlist(items_used, use.names = F), "category"]
round(sort(table(categories_used) / length(categories_used), decreasing=T), 3)
```
```{r}
round(sort(table(cdi$category) / nrow(cdi), decreasing = T), 3)
```

```{r}
cl <- makeCluster(detectCores())
sim_results_st <- mirtCAT(mo = mo, method = "MAP", criteria = "MI", start_item = "MI", local_pattern = responses, cl = cl, design = list(min_items = 10, min_SEM = 0.1, max_items = 50, thetas.start = start_thetas - 2))
save.image("Data/items_usage.RData")
```

Most popular items:

```{r}
raw_responses <- laply(sim_results_st, function(x) x$raw_responses)
item_usage <- round(apply(raw_responses, 2, function(x) length(which(!is.na(x))))/nrow(responses), 3)
most_popular <- cbind(cdi, item_usage)
most_popular <- most_popular[order(most_popular$item_usage, decreasing=T), ]
most_popular
```

Most popular categories:

```{r}
items_used <- apply(raw_responses, 1, function(x) which(!is.na(x)))
categories_used <- cdi[unlist(items_used, use.names = F), "category"]
round(sort(table(categories_used) / length(categories_used), decreasing=T), 3)
```

Check correlations by age groups:

* [18,21)

```{r}
cor(thetas[which(responses_demo$months < 21)], as.numeric(fscores)[which(responses_demo$months < 21)])
```

* [21,24)

```{r}
cor(thetas[which(responses_demo$months < 24 & responses_demo$months >= 21)], as.numeric(fscores)[which(responses_demo$months < 24 & responses_demo$months >= 21)])
```

* [24,27)

```{r}
cor(thetas[which(responses_demo$months < 27 & responses_demo$months >= 24)], as.numeric(fscores)[which(responses_demo$months < 27 & responses_demo$months >= 24)])
```

* [27,30)

```{r}
cor(thetas[which(responses_demo$months < 30 & responses_demo$months >= 27)], as.numeric(fscores)[which(responses_demo$months < 30 & responses_demo$months >= 27)])
```

* [30,33)

```{r}
cor(thetas[which(responses_demo$months < 33 & responses_demo$months >= 30)], as.numeric(fscores)[which(responses_demo$months < 33 & responses_demo$months >= 30)])
```

* [33,36]

```{r}
cor(thetas[which(responses_demo$months <= 36 & responses_demo$months >= 33)], as.numeric(fscores)[which(responses_demo$months <= 36 & responses_demo$months >= 33)])
```